### ISSUE TITLE
Improve code coverage upto 90%

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/bridge_common#10]
We need to collectively start improving the unit test code coverage for this project.

Current coverage: https://coveralls.io/github/Tendrl/bridge_common

Unit tests framework: http://docs.openstack.org/developer/oslotest/

How to write unit tests: http://docs.openstack.org/developer/horizon/topics/testing.html

Contribute patches here: https://github.com/Tendrl/bridge_common/tree/master/bridge_common/tests

Lets work on this issue together to get code coverage up to 90%, please share doubts/inputs on this issue itself

**Comment by GowthamShanmugam** [comment]
unit test added https://github.com/Tendrl/bridge_common/pull/16/commits/f57de92c3f56651b32679b6589907dd561aec25f

**Comment by GowthamShanmugam** [comment]
looging file is imported in __init__() file inside etcdobj module, so module load time it gives error like no dir/file in /var/log/tendrl, travis ci shows error for all of the patches. This is not related to testing, it may affect all patches i think. I had found this problem when i send unit testing patch.

**Comment by r0h4n** [comment]
I see, it seems to be because of importing LOG into every python file. Please remove that import and create LOG for each file you are dealing with, that will help resolve this problem

**Comment by GowthamShanmugam** [comment]
are you saying
 from bridge_common import logging 
and then 
LOG = logging.getLogger(__name__)
in each file

**Comment by r0h4n** [comment]
Yea, then you can mock the LOG wherever required for unit tests

**Comment by GowthamShanmugam** [comment]
my test cases are almost covered 57% of code in bridge_common, renaming 40-45 code coverage is based on hacking folder. But problem is hacking folder is already in tests folder. those are testing codes also. I cant test it again. So we have to remove that folder from code coverage.

**Comment by GowthamShanmugam** [comment]
@r0h4n, In etcdobj file bridge_common.logging is not imported , again log is intialized with new variable is that bug?

**Comment by r0h4n** [comment]
Closing this one
