### ISSUE TITLE
Definition YAML files should have flags to control the visibility of entities

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/bridge_common#13]
Both the state and the operations definition files should allow the visibility of all the entities (objects, atoms, attributes and flows) via the API, to be controlled. This enables a workflow where the supporting backend implementation would first have to implement the support for a certain entity. Once the implementation is complete, that entity would then be marked as available for manipulation via the API.

To do this, the definition file needs to support:

- a global default visibility flag, and

- per entity visibility flags that overrides the global default.

**Comment by r0h4n** [comment]
Fixed https://github.com/Tendrl/bridge_common/blob/master/etc/samples/tendrl_definitions_generic-0.1.sample.yaml#L7
