### ISSUE TITLE
install instructions documentation

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/bridge_common#17]
There should be document which describes:

    what software should be installed and how should be configured before installing Tendrl
    Tendrl installation process
    Tendrl post installation steps like configuration, service starting and so on

[was originally at https://tendrl.atlassian.net/browse/TEN-36]

**Comment by mbukatov** [comment]
There is a typo in the installation instructions, the proposed fix is here: https://github.com/Tendrl/bridge_common/pull/28

**Comment by r0h4n** [comment]
Seems like we can close this one
